import type { Metadata } from "next";
import "../styles/index.scss";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";

export const metadata: Metadata = {
  title: "Orchestre Universitaire de Metz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
