import type { Metadata } from "next";
import "../styles/index.scss";
import Image from "next/image";
import logo from "../../public/assets/logo.jpg";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <nav>
          <div>
            <h1>Orchestre musicale de metz</h1>
            <Image src={logo} alt="Orchestre universitaire de metz" />
          </div>
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
