import type { Metadata } from "next";
import "../styles/index.scss";
import Image from "next/image";
import logo from "../../public/assets/logo.jpg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <nav>
          <p>Orchestre musicale de metz</p>
          <Image src={logo} alt="Orchestre universitaire de metz" />
        </nav>
        {children}
      </body>
    </html>
  );
}
